### ISSUE TITLE
Priprava objekta

### ISSUE THREAD

**Issue by tinmarkon** [tinmarkon/FP-BKP#1]
Ali je potrebna priprava classa, tako da potem te funkcije pripravima kot metode v tem classu? 
Zanima naju tudi ali je potrebno tesitrati časovno zahtevnost glede na obseg podatkov?

**Comment by jaanos** [comment]
Kako si organizirata kodo, je vajina izbira. Objektno usmerjen pristop je vsekakor ena možnost, ni pa nujen.

**Comment by jaanos** [comment]
Kar se pa tiče merjenja časovne zahtevnosti, je to vsekakor dobrodošlo. Tako lahko tudi primerjata s teoretično časovno zahtevnostjo algoritma.
