### ISSUE TITLE
Zakjuček projetka

### ISSUE THREAD

**Issue by tinmarkon** [tinmarkon/FP-BKP#2]
Projekt je zaključen. Poganja se s pomočjo datoteke Generiranje_podatkov, kjer je za različno velikost podatkov testirama časovno zahtevnost. Zanima naju ali je potrebno še kaj dodati?

**Comment by jaanos** [comment]
Če vajin program deluje, kot pričakujeta, potem je to to, kar se tiče programerskega dela. Bi pa opozoril, da eno poganjanje za nekaj velikosti problema, kot izgleda, da program naredi, ne bo dovolj - za vsako velikost program poženita večkrat, da bosta lahko ocenila povprečja in variabilnost rezultatov in časov poganjanja ter to predstavila z grafi v poročilu.

Število poganjanj je seveda odvisno od tega, koliko časa teče vajin program - lahko ga tudi prilagodita glede na velikost problema. Svetujem tudi, da poskusita tudi z večjimi velikostmi, če bo seveda to izvedljivo.
